[package]
name = "dynparser"
version = "0.1.0"
authors = ["maiquel <jleahred@gmail.com>"]
license = "GPL-3.0"
description = "Dynamic parer"
readme = "README.adoc"
repository = "https://github.com/jleahred/dynparser"
keywords = ["parsing", "dynamic"]

[dependencies]
