[package]
name = "dinpeg"
version = "0.1.0"
authors = ["maiquel <jleahred@gmail.com>"]
build = "build.rs"

[dependencies]
indentation_flattener = "0.1.0"


[build-dependencies]
peg = { version = "0.5" }